finish_week1HW
Lidemy/mentor-program-5th-yichennnn36 pull request #1
Opened 2021-04-15 17:24 UTC by yichennnn36

2021-04-16 16:03 UTC, cwc329 requested changes

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw1.md
> +1. 使用 `git clone` 將檔案存至電腦
只要 `git clone` 兩個字就可以了嗎？

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw3.md
> +這樣就完成了！
滿完整的，說明清楚，不錯。

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw4.md
> +說白話一點就是指，它可以幫你保存更新過的歷史紀錄，同時也可以顯示編輯的內容，以及避免多人協作時，你的檔案被覆蓋掉的風險等等......，運作的模式可以想像成，幫「蔡哥的笑話」加入版本控制，每經過一次修改，電腦就會幫你新增一個資料夾並儲存這些編輯紀錄，這樣版本就算很多，也可以清楚的管理舊與新的檔案。
是直接新增一個資料夾嗎？

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw4.md
> +
那詳細要怎麼把一個笑話或者一個專案做版本控制呢？

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw5.md
> +前端也可以想成是餐廳的外場，視線所及的範圍、裝潢、環境和菜單等，轉換成網頁就是使用者可以看到的介面呈現；而後端就是餐廳的後場，備料，並端出外場需要的菜色，網頁中負責處理後台資料庫的溝通，接收前端的指令（request）並提供相對應的資料（response），再由前端顯示。
一般來說，網頁不會是後端的東西。這邊的觀念可能要再釐清一些。
用比喻可以快速進入狀況，不過最好的方式還是用自己的話解釋一遍，不要只靠比喻。

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw5.md
> +3. 將結果回傳給伺服器
如果伺服器進到資料庫，那還需要資料庫回傳結果嗎？

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw5.md
> +4. Google 瀏覽器呈現所看到的網頁內容
網頁內容又是從哪來的呢？

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw5.md
> +7. 瀏覽器發送 request 給 172.217.160.78（google IP 位址）
在這邊瀏覽器要怎麼知道 google.com 的 IP 呢？

2021-04-16 16:03 UTC, cwc329 commented on homeworks/week1/hw5.md
> +4. Google 瀏覽器呈現所看到的網頁內容
同 line 12, line 13

2021-04-16 16:06 UTC, cwc329 commented
CLI 部分寫得不錯，另外有查 DNS 與 DNS cache 不錯，讚讚。
如果可以把 git 以及 前後端的觀念在弄清楚會更好。
作業看是要在這個 PR 改完，或者再開一個 branch 訂正也行。

2021-04-17 01:09 UTC, yichennnn36 commented on homeworks/week1/hw1.md
> +1. 使用 `git clone` 將檔案存至電腦
1. 檔案 clone 到電腦：`git clone https://github.com/Lidemy/mentor-program-5th-yichennnn36.git`

2021-04-19 12:06 UTC, merged